export { default as Hero } from './Hero'
export { default as Navigation } from './Navigation'
export { default as About } from './About'
export { default as Funding } from './Funding'
export { default as Contact } from './Contact'
export { default as Footer } from './Footer'
